### ISSUE TITLE
Fingerprint generation

### ISSUE THREAD

**Issue by gokhantahil** [UnixJunkie/molenc#137]
Hello, 

I wanted to generate fingerprint for some molecules.

I tried to use python version or ocaml version. In ocaml's version, I couldn't use fingerprint.ml or fp_mol.ml. Everything that I've done had an "Unbound value" error. In python, I even couldn't reach there. 

Can you help me?

**Comment by UnixJunkie** [comment]
you probably want to read this: https://www.rdkit.org/docs/GettingStartedInPython.html

**Comment by gokhantahil** [comment]
I'm currently using fingerprint such as ECFP, MHFP, RDKit fingerprint and MACCS Keys fingerprint. 

In your repository, I've seen "The implemented fingerprint is J-L Faulon's "Signature Molecular Descriptor" (SMD [1])". I'm not sure if I can generate such fingerprint with molenc. At least, I couldn't generate. That's why I was asking.

Thanks.

**Comment by UnixJunkie** [comment]
In rdkit, use counted atom pairs, it should be pretty similar.

**Comment by UnixJunkie** [comment]
Or, a counted version of ECFP should be pretty similar to Faulon's FP, I
would need to check.

**Comment by gokhantahil** [comment]
The problem is it ECFP can not detect the stereochemistry. Even with the version of usechirality, it generates same bits for lots of stereoisomers. Faulon's approach is looking like it can generate different bits for such molecule. But also, I'm not sure if it's possible.

**Comment by gokhantahil** [comment]
Also, I need a fixed-size representation. That's why I use bits, not counted atom pairs. I'll check what I do generate with counted atom pairs and if I can use it.

**Comment by UnixJunkie** [comment]
rdkit is supposed to be able to handle chirality:
---
GetMorganGenerator(...)
    GetMorganGenerator([  (int)radius=3 [, (bool)countSimulation=False [, (bool)includeChirality=False [, (bool)useBondTypes=True [, (bool)onlyNonzeroInvariants=False [, (bool)includeRingMembership=True [, (AtomPairsParameters)countBounds=None [, (int)fpSize=2048 [, (AtomPairsParameters)atomInvariantsGenerator=None [, (AtomPairsParameters)bondInvariantsGenerator=None [, (bool)includeRedundantEnvironments=False]]]]]]]]]]]) -> FingeprintGenerator64 :
        Get a morgan fingerprint generator
        
          ARGUMENTS:
            - radius:  the number of iterations to grow the fingerprint
            - countSimulation: if set, use count simulation while generating the fingerprint
            - includeChirality: if set, chirality information will be added to the generated fingerprint
            - useBondTypes: if set, bond types will be included as a part of the default bond invariants
            - countBounds: boundaries for count simulation, corresponding bit will be  set if the count is higher than the number provided for that spot
            - fpSize: size of the generated fingerprint, does not affect the sparse versions
            - atomInvariantsGenerator: atom invariants to be used during fingerprint generation
        
        This generator supports the following AdditionalOutput types:
            - atomToBits: which bits each atom is the center of
            - atomCounts: how many bits each atom sets
            - bitInfoMap: map from bitId to (atomId1, radius) pairs
        
          RETURNS: FingerprintGenerator
---

Maybe, when reading molecules in, you are somehow discarding the chirality info?
